apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-deployment
  namespace: sonar
spec:
  replicas: 1  # You can scale this if needed
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - name: sonar
          image: sonarqube:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonar-storage
              mountPath: /opt/sonarqube/data  # This is where SonarQube stores its data
      volumes:
        - name: sonar-storage
          persistentVolumeClaim:
            claimName: sonar-pvc

