apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  namespace: sonar
spec:
  selector:
    app: sonar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer  # You can change this to ClusterIP or NodePort as per your need

